/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lkpower_oaandroid_MainActivity */

#ifndef _Included_com_lkpower_oaandroid_MainActivity
#define _Included_com_lkpower_oaandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
