/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lkpower_sign_SignCore_SignCoreInner */

#ifndef _Included_com_lkpower_sign_SignCore_SignCoreInner
#define _Included_com_lkpower_sign_SignCore_SignCoreInner
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
